### ISSUE TITLE
Not getting full email link.

### ISSUE THREAD

**Issue by AlishahMughal123** [s0md3v/ote#2]
Like if website is sending a link in base64 or having more characters, then it`s not showing full email link in terminal.

![image](https://user-images.githubusercontent.com/52525188/103786601-6cf3d880-505e-11eb-9090-56df0c119c2a.png)

**Comment by s0md3v** [comment]
Thanks for reporting the issue. Is it possible for you share the link of the website so I can register and debug myself?

Or you can attach the email body with all the sensitive information redacted.

**Comment by AlishahMughal123** [comment]
My pleasure bud,
https://site.com/ls/click?upn=vTuJ3QTk08CUb3w9LKUot79QVXtAHAMJeWZ1X3cUiwZ13IzceuPh1c7AaRoFQS6Eh6zuv0KH84Ik1YmkwutCWj8HnXCtE6CoEsCXe8696cJ-2BHHcNOxy4R2H2ryQ17R2xCc9sH6s1R4Zd70g4bsKhYCm1BvtdN-2BtJ882toHuP1xQ-3DNd8Q_CQzcozIP09iLwsnOhasdasdasdasdVyBmTuznbPzfdESe2WbNZ-2FsJvxfghZyXzJzPQkq11y14Z0iz9UvoRZChLWkdQc1QCfbDGzhefQqB1jALyuWuk70dQDzP9LJRgEEhS2CEKCNVx6bUsLZtrs-2BjRkXxdjSttgMs7gwkkKv9ZLWBtVXQsacUVnkcZF8O3iK5bQR1PhC65SeRX9K-2Bh-2BX4PW83XrRPOtppr7T8PpBFpZoRzgJ3ftX5YVtCHjN9Uo6Rig3oj-2FvyAK4RSjCUiI4RJ1OB-2FBkRcA8YbtmYcE06Q0GmEIB6-2FH5kc1rPqoZhU031Wv69hqCdDOA3QDnBlUfLnu9n-2BXKphaDOlQb9WFYz04IFF3LoGLru-2FgN1-2F0LvDrBN5WyoYsFarX7HbND7vmeMPglFtSXvOFxRD2vwmJqA6qk5Blal-2BSgUBMgbv-2BEqMwVBxn09ipDfe9EPJ5X-2Bgx5wKSgnYrqTwEu42UR4Y-3D

**Comment by s0md3v** [comment]
That's just the link.....not the email body.

**Comment by s0md3v** [comment]
Thanks for reporting, this issue has been fixed.

**Comment by AlishahMughal123** [comment]
Cool ✌ Pleasure 🙂
