### ISSUE TITLE
ote: command not found

### ISSUE THREAD

**Issue by asolab** [s0md3v/ote#4]
successfully installed but the ''ote'' command is not working, all other are not working from my end.  any idea?

**Comment by s0md3v** [comment]
Can't reproduce.

![Screenshot_2021-01-10_14-44-51](https://user-images.githubusercontent.com/26716802/104118957-74fb9300-5352-11eb-8fd9-55d5edc85072.png)

**Comment by s0md3v** [comment]
1. Make sure `python3` and `pip3` are installed
2. Install `ote` using `pip3`

That's all the advice I can offer.

**Comment by asolab** [comment]
Done! Thanks Boss
